### PR TITLE
Replace broken video links with github hosted videos

### PR DESCRIPTION
**Pull request by jinyus**
In response to: https://github.com/zezo357/flutter_meedu_videoplayer_example/issues/1#issuecomment-1801602779

### CODE REVIEW

**Comment by zezo357** [comment]
Thank you for your contribution, but I think adding to assets will increase apps size, so I think just uploading to GitHub and using the links is enough

**Comment by jinyus** [comment]
The videos aren't included with the app. I just named the folder `assets`

**Comment by zezo357** [comment]
Also I am confused about the addition of index.html!? Why is it needed?

**Comment by zezo357** [comment]
> The videos aren't included with the app. I just named the folder `assets`

Oh, my bad I thought it was related to the flutter assets, 

Will check it tomorrow then and if all is good will merge

**Comment by jinyus** [comment]
I was trying to get github pages to recognize the `assets` folder as hostable and though it needed an `index.html`. That can be deleted.

**Comment by zezo357** [comment]
Ok, thank you,



Keep in mind if you are still using the package I had set it as discounted some time ago,since I am not planning to keep updating it and moved to help with media_kit since they are using flutter integrated notifiers and included tests and much more customization, and hopefully all of the features in this package will be implemented better there

**Comment by jinyus** [comment]
I'm not using the package; I just came across the broken docs and thought I should report the issue.

**Comment by zezo357** [comment]
Wow, thank you very much ❤️


I saw you have a repo for benchmark on data analysis using different programming languages, love the idea and the amount of Languages tested



I always thought dart on the slow side but python is waaaay slower


I wanted to do a backend benchmark repo too, but never got the time to do it 😢, hopefully one day since you encouraged me ❤️

**Comment by abdelaziz-mahdy** [comment]
since i forgot to merge this, and https://github.com/abdelaziz-mahdy/flutter_meedu_videoplayer/pull/186 fixes the urls too, and uses a hosted url else where, i think i will close this

i am very sorry for forgetting to merge it.

**Pull request closed without merging**
